In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from mlxtend.frequent_patterns import apriori


# read dataframe from local file
df = pd.read_csv('../datasets/coffee_shop.csv', sep=';')
df

,Id,Coffee,Tea,Hot_chocolate,Cheese,Sausage,Veggie_deli_slices,Cucumber,Tomato,Juice,Milk,Dark_bread,White_bread,Sweet_bun,Croissant,Fruit_chunks,Smoothie
0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
2,3,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
3,4,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
5,6,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
8,9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
9,10,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
10,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN
13,14,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
14,15,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN
15,16,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0
16,17,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
17,18,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
19,20,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
21,22,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
22,23,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN
24,25,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
29,30,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
30,31,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
32,33,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
33,34,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
35,36,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
36,37,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
37,38,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
38,39,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
39,40,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
40,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
41,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN
43,44,NaN,NaN,1.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
44,45,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN
45,46,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
46,47,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
47,48,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,49,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
49,50,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
50,51,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0
51,52,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
52,53,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,54,NaN,1.0,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN
54,55,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,56,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,57,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,58,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,59,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
59,60,1.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0

In [5]:
df = df.drop(columns='Id')

df = df.fillna(False)
df = df.apply(lambda x: x.map(lambda y: True if y == 1.0 else y))
df

,Coffee,Tea,Hot_chocolate,Cheese,Sausage,Veggie_deli_slices,Cucumber,Tomato,Juice,Milk,Dark_bread,White_bread,Sweet_bun,Croissant,Fruit_chunks,Smoothie
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,True,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False
2,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
5,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
6,False,False,True,True,False,False,True,False,False,False,True,False,False,False,False,False
7,False,False,True,True,False,True,False,False,False,False,True,False,False,False,False,True
8,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
9,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False
10,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
13,False,False,True,True,True,False,False,False,False,False,False,True,False,False,False,False
14,True,False,False,False,True,False,False,False,False,True,False,False,True,True,False,False
15,False,True,False,False,False,True,False,False,False,True,False,False,False,False,True,True
16,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
17,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
20,True,False,False,False,False,True,True,True,False,False,True,False,False,False,False,True
21,True,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False
22,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,True,False,False,False,False,True,True,False,False,True,False,False,False,True,False
24,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
25,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
26,True,False,False,True,True,False,True,False,True,False,False,False,False,False,False,False
27,True,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False
28,True,False,False,True,True,False,True,False,True,True,False,False,False,False,False,False
29,True,False,False,False,False,True,True,True,False,False,True,False,False,False,False,True
30,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,True,False,False,True,True,False,False,True,False,False,False,True,False,False,False,False
32,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False
33,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
35,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
36,False,False,True,True,False,False,True,False,False,False,True,False,False,False,False,False
37,False,False,True,True,False,True,False,False,False,False,True,False,False,False,False,True
38,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
39,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False
40,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
43,False,False,True,True,True,False,True,False,False,False,False,True,False,False,False,False
44,True,False,False,False,True,False,False,False,False,True,False,False,True,True,False,False
45,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False
46,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
47,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48,True,False,True,False,False,True,False,False,True,False,False,False,False,False,True,False
49,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
50,True,False,False,False,False,True,True,True,False,False,True,True,False,False,False,True
51,True,False,False,False,False,True,True,False,False,False,True,False,False,False,False,True
52,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
53,False,True,False,False,True,False,True,True,False,False,True,False,True,False,True,False
54,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
55,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
56,True,False,False,True,True,False,True,False,True,False,False,False,False,False,False,False
57,True,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False
58,True,False,False,True,False,False,True,False,True,True,False,False,False,False,False,False
59,True,True,False,False,False,True,True,True,False,False,True,False,False,False,False,True

In [6]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.633333                                           (Coffee)
1   0.116667                                              (Tea)
2   0.150000                                    (Hot_chocolate)
3   0.366667                                           (Cheese)
4   0.233333                                          (Sausage)
5   0.233333                               (Veggie_deli_slices)
6   0.316667                                         (Cucumber)
7   0.200000                                           (Tomato)
8   0.116667                                            (Juice)
9   0.183333                                             (Milk)
10  0.266667                                       (Dark_bread)
11  0.116667                                      (White_bread)
12  0.150000                                        (Sweet_bun)
13  0.100000                                        (Croissant)
14  0.133333                                     (Fruit_chunks)
15  0.166667                                         (Smoothie)
16  0.266667                                   (Cheese, Coffee)
17  0.183333                                  (Sausage, Coffee)
18  0.133333                       (Veggie_deli_slices, Coffee)
19  0.233333                                 (Cucumber, Coffee)
20  0.150000                                   (Tomato, Coffee)
21  0.116667                                    (Juice, Coffee)
22  0.100000                                     (Milk, Coffee)
23  0.166667                               (Dark_bread, Coffee)
24  0.100000                                 (Smoothie, Coffee)
25  0.100000                            (Cheese, Hot_chocolate)
26  0.150000                                  (Cheese, Sausage)
27  0.183333                                 (Cheese, Cucumber)
28  0.100000                                    (Juice, Cheese)
29  0.133333                               (Dark_bread, Cheese)
30  0.100000                             (Sausage, White_bread)
31  0.100000                     (Veggie_deli_slices, Cucumber)
32  0.133333                   (Dark_bread, Veggie_deli_slices)
33  0.166667                     (Veggie_deli_slices, Smoothie)
34  0.166667                                 (Tomato, Cucumber)
35  0.233333                             (Dark_bread, Cucumber)
36  0.166667                               (Dark_bread, Tomato)
37  0.116667                             (Dark_bread, Smoothie)
38  0.100000                             (Croissant, Sweet_bun)
39  0.116667                          (Cheese, Sausage, Coffee)
40  0.133333                         (Cheese, Cucumber, Coffee)
41  0.100000                            (Juice, Cheese, Coffee)
42  0.100000             (Veggie_deli_slices, Cucumber, Coffee)
43  0.100000           (Dark_bread, Veggie_deli_slices, Coffee)
44  0.100000             (Veggie_deli_slices, Smoothie, Coffee)
45  0.133333                         (Tomato, Cucumber, Coffee)
46  0.166667                     (Dark_bread, Cucumber, Coffee)
47  0.133333                       (Dark_bread, Tomato, Coffee)
48  0.100000                     (Dark_bread, Cheese, Cucumber)
49  0.100000         (Dark_bread, Veggie_deli_slices, Cucumber)
50  0.116667         (Dark_bread, Veggie_deli_slices, Smoothie)
51  0.166667                     (Dark_bread, Tomato, Cucumber)
52  0.100000  (Dark_bread, Veggie_deli_slices, Cucumber, Cof...
53  0.133333             (Dark_bread, Tomato, Cucumber, Coffee)

In [7]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)

rules = rules.sort_values(by='confidence', ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
5,(Juice),(Coffee),0.116667,0.633333,0.116667,1.0,1.578947,1.0,0.042778,inf,0.415094,0.184211,1.000000,0.592105
19,(Smoothie),(Veggie_deli_slices),0.166667,0.233333,0.166667,1.0,4.285714,1.0,0.127778,inf,0.920000,0.714286,1.000000,0.857143
27,(Croissant),(Sweet_bun),0.100000,0.150000,0.100000,1.0,6.666667,1.0,0.085000,inf,0.944444,0.666667,1.000000,0.833333
66,"(Dark_bread, Smoothie)",(Veggie_deli_slices),0.116667,0.233333,0.116667,1.0,4.285714,1.0,0.089444,inf,0.867925,0.500000,1.000000,0.750000
76,"(Dark_bread, Veggie_deli_slices, Cucumber)",(Coffee),0.100000,0.633333,0.100000,1.0,1.578947,1.0,0.036667,inf,0.407407,0.157895,1.000000,0.578947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,(Dark_bread),(Cheese),0.266667,0.366667,0.133333,0.5,1.363636,1.0,0.035556,1.266667,0.363636,0.266667,0.210526,0.431818
59,(Dark_bread),"(Tomato, Coffee)",0.266667,0.150000,0.133333,0.5,3.333333,1.0,0.093333,1.700000,0.954545,0.470588,0.411765,0.694444
33,"(Cheese, Coffee)",(Cucumber),0.266667,0.316667,0.133333,0.5,1.578947,1.0,0.048889,1.366667,0.500000,0.296296,0.268293,0.460526
68,(Veggie_deli_slices),"(Dark_bread, Smoothie)",0.233333,0.116667,0.116667,0.5,4.285714,1.0,0.089444,1.766667,1.000000,0.500000,0.433962,0.750000
94,(Dark_bread),"(Tomato, Cucumber, Coffee)",0.266667,0.133333,0.133333,0.5,3.750000,1.0,0.097778,1.733333,1.000000,0.500000,0.423077,0.750000

### Lift: a derived metric

In [8]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=2)

rules = rules.sort_values(by='lift', ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
16,(Croissant),(Sweet_bun),0.100000,0.150000,0.100000,1.000000,6.666667,1.0,0.085000,inf,0.944444,0.666667,1.000000,0.833333
17,(Sweet_bun),(Croissant),0.150000,0.100000,0.100000,0.666667,6.666667,1.0,0.085000,2.700000,1.000000,0.666667,0.629630,0.833333
69,"(Dark_bread, Coffee)","(Veggie_deli_slices, Cucumber)",0.166667,0.100000,0.100000,0.600000,6.000000,1.0,0.083333,2.250000,1.000000,0.600000,0.555556,0.800000
70,"(Veggie_deli_slices, Cucumber)","(Dark_bread, Coffee)",0.100000,0.166667,0.100000,1.000000,6.000000,1.0,0.083333,inf,0.925926,0.600000,1.000000,0.800000
57,(Smoothie),"(Dark_bread, Veggie_deli_slices)",0.166667,0.133333,0.116667,0.700000,5.250000,1.0,0.094444,2.888889,0.971429,0.636364,0.653846,0.787500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,"(Juice, Coffee)",(Cheese),0.116667,0.366667,0.100000,0.857143,2.337662,1.0,0.057222,4.433333,0.647799,0.260870,0.774436,0.564935
5,(Veggie_deli_slices),(Dark_bread),0.233333,0.266667,0.133333,0.571429,2.142857,1.0,0.071111,1.711111,0.695652,0.363636,0.415584,0.535714
4,(Dark_bread),(Veggie_deli_slices),0.266667,0.233333,0.133333,0.500000,2.142857,1.0,0.071111,1.533333,0.727273,0.363636,0.347826,0.535714
45,"(Cheese, Cucumber)",(Dark_bread),0.183333,0.266667,0.100000,0.545455,2.045455,1.0,0.051111,1.613333,0.625850,0.285714,0.380165,0.460227
46,(Dark_bread),"(Cheese, Cucumber)",0.266667,0.183333,0.100000,0.375000,2.045455,1.0,0.051111,1.306667,0.696970,0.285714,0.234694,0.460227